include: "rules/rules.smk"


rule all:
    input:
        # Run the same workflow for various conditions via `expand` (original/grayscale/equalized/blurred)
        expand(
            "../results/histograms/{transformation}_hist.png",
            transformation=["original", "grayscale", "equalized", "blurred"],
        ),
